-- NORMAL WAY TO CREATE TABLE
CREATE TABLE PERSON(
	id INT,
	name VARCHAR(30),
	phone VARCHAR(15),
	location VARCHAR(15),
	CONSTRAINT pk_name PRIMARY KEY(id)
)
-- CREATE TABLE FROM EXISTING TABLE
	SELECT name,phone
	INTO PHONE
	FROM PERSON

SELECT * FROM PERSON
SELECT * FROM PHONE


-- ALTERING TABLE
ALTER TABLE PERSON
ADD email VARCHAR(30)

SELECT * FROM PERSON

ALTER TABLE PERSON
DROP COLUMN location

SELECT * FROM PERSON


--DROP
DROP TABLE PHONE
